B2 taylor
opanopan/Panichev_py111 pull request #22
Opened 2021-01-26 05:38 UTC by opanopan

2021-01-27 09:54 UTC, EnotYoyo requested changes
Это задание рассчитано на то, что Вы эффективно будете считать члены ряда (зная числитель и знаменатель с предыдущего шага можно эффективно посчитать следующий)

2021-01-27 10:08 UTC, opanopan commented
> Это задание рассчитано на то, что Вы эффективно будете считать члены ряда (зная числитель и знаменатель с предыдущего шага можно эффективно посчитать следующий)

Да, тут были вопросы у меня. На лекции нам рассказали вроде бы в целом про эти ряды, было не очень понятно, альтернативные лекции у меня не загружаются на dl-ido, на слайдах сказано "реализовать вычисление следующих рядов" и формулы,  в интернете какая-то жесткая математика, на практике Вы нам сказали "оставить на потом" :)

Но я в целом понял, мне видимо надо не возводить в степень каждый раз, а рекурсивно умножать/прибавлять к предыдущему результату. Попробую, спасибо.

2021-01-27 10:11 UTC, EnotYoyo commented
Не рекурсивно, а просто сохраняя результат с предыдущего шага. 
Математика Вам особо тут не нужна (поскольку Вам не нужно знать, почему эти суммы приближенно равны e^x или синусу). Вам нужно реализовать сам подсчет. :)

2021-01-28 16:51 UTC, opanopan commented
> Не рекурсивно, а просто сохраняя результат с предыдущего шага.
> Математика Вам особо тут не нужна (поскольку Вам не нужно знать, почему эти суммы приближенно равны e^x или синусу). Вам нужно реализовать сам подсчет. :)

Спасибо, переделал.

2021-01-29 17:08 UTC, EnotYoyo approved these changes
Принято

2021-01-29 18:11 UTC, merged